name: Deploy Sphinx Docs

on:
  push:
    branches:
      - docs-deployment  # Change to `main` after testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Build Sphinx Documentation
        run: poetry run sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git worktree add gh-pages
          rm -rf gh-pages/*
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy latest Sphinx docs"
          git push origin gh-pages --force
