name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Change this to docs-deployment for testing, later change to main.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Build Sphinx Documentation
        run: poetry run sphinx-build -b html docs docs/_build/html
      
